import "~/styles/globals.css";

import { Inter } from "next/font/google";

import Navbar from "./components/nab-bar";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Your IELTS Prep Partner",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`font-sans ${inter.variable} mx-4 flex flex-col bg-sky-950 text-white`}
      >
        <header className="flex-1">
          <Navbar />
        </header>
        <main className="min-h-[90vh] shrink-0">{children}</main>
        <footer className="flex-1 p-3 text-center">@Lada496</footer>
      </body>
    </html>
  );
}
